stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build"
        - echo "testing"
    artifacts:
        paths:
            - "bin/"
        
test:
    stage: test
    script: 
        - "dotnet test"
        - echo "testing"

